kind: pipeline
name: Distribute Documentation

steps:

- name: Build The Documentation
  image: squidfunk/mkdocs-material
  pull: if-not-exists
  commands:
    - mkdocs build
    - mkdir /drone/tmp
    - cp -rf /drone/src/site/* /drone/tmp/
    - rm -rf *
    - mv /drone/tmp/* /drone/src/
  when:
    branch:
    - DEV
    event:
    - push

- name: Transfer Source
  image: appleboy/drone-scp
  settings: 
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    password:
      from_secret: scp_password
    source: 
      - '*'
      - '.*'
    target: /var/www/products/docs.zubzet.de/prod
    rm: true
  when:
    branch:
    - DEV
    event:
    - push