# Project information
site_name: ZubZet
site_url: https://docs.zubzet.de
site_author: Alexander Zierhut
site_description: A modular, prototyping speed oriented PHP Framework.

# Repository
repo_name: ZubZet/zubzet
repo_url: https://git.zierhut-it.de/Zierhut-IT/z_framework
edit_uri: https://git.zierhut-it.de/Zierhut-IT/z_framework/src/branch/DEV/docs

# Copyright
copyright: Copyright &copy; 2018 - 2020 Zierhut IT - Alexander Zierhut

# Theme
theme:
    name: 'material'

# Navigation
nav:
    - Getting Started: Getting Started.md